working on tmobile -- have to run it less often

diff --git a/casperjs/run_bandwidth b/casperjs/run_bandwidth
--- a/casperjs/run_bandwidth
+++ b/casperjs/run_bandwidth
@@ -14,11 +14,11 @@ until [ $n -ge 3 ]; do
 done
 
 
-# retry n times
-n=0
-until [ $n -ge 3 ]; do
-    casperjs ~/dev/bandwidth/tmobile/archive.js
-    [  $? -eq 0 ] && break
-    n=$[$n+1]
-    sleep 10
-done
+# # retry n times
+# n=0
+# until [ $n -ge 3 ]; do
+#     casperjs ~/dev/bandwidth/tmobile/archive.js
+#     [  $? -eq 0 ] && break
+#     n=$[$n+1]
+#     sleep 10
+# done
